language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt

env:
  global:
  - GH_USER_NAME: "chaostoolkit-ci"
  - secure: "JHKFfue7dXjvK6XbuqRlVuDZUWkZKbabHAwvYtQMTS0rPHEOP2BL6+xHcYHWBB817wNXm5iuxkSYaQQxTObe1KKQBulLEI8myn3oW544n+pxNfOKgA/oA88AXnVHeWT+/CwOJ56BH2kbTgC3zX6sC8EXoorMCBXz40xDB/XBzVS+H01N+j3GQ+Z14nOqpbcuvl5H1cZkAbME3hf8gEw1OFn9LwpxVD+lERR+A+2nve71yvhMOzcI7pI8+oM1HHqP/vdANpgY7M5n9tO+UWY2SXdhkf+VqAZlM77tJSYaQ9OVKdkfKxpwqr5B9bTWJUXfWLzR9az2Ar28Ou5OO5KCDgOIjFsnP31DCoFoCcChrbp2y0oW2uS5iDdSoih315zQ/DgnecnIQuhCQMf7bbnSZWxw7/XTdNwKN4hE5kZVmRRP8cIyQ/oZmlD5HHRmg8H9JRqDUgHsInchGqaMYRWCdnwDbzmLClhT1Lm9Vj8Qx9vUEHnaHFQRgEuAVWZHIF/qekd+iCBjZ2WeDPUQdzzfg5GPz6AqG7dG4eLZsoHZlp4m1HNdZgNf5Vdj/2g2aea61WvxaSZxMFfankpi62aT9t8gsQj9sXsuanNtmYacyAhNHxvhjjM5f1nlEPxWtBs7rTtVZbTVDcAKUCK6jSq8yHyuTKQNxWQbP+XE82U+Fp8="

script: 
  - bash ci.bash

branches:
  except:
  - gh-pages