language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt

env:
  global:
  - secure: "qB82Xe5t7CaSmxYgSVTaB1OIgEnT+PC3E02nm2MIGH84pI17l8OZMEK0jN78r4rEWzKdIUygKn+uhH8NzL1SFWUVbpNPmQa9a9VLLhGwn7DaOYF9PF0Mlv+WMkI5HswSgtTaGb6x/wNg/mgUeMgsfPAryql9uJ1P4HA6dclUy22FSCRIugitaWla8JqUsRfJGf29gthThdsv991Vjoumg4KkUlVLhCqrs6MupUiX+HhNzJyJDYoMud/IcaNNWcg6xy4AUGtrhudv+LcG4WLr8EfBXfdKZmS3bReujOTWqyNo4k2K02wArpT7tRRlDcZPKmkpjCIYijD0fT9gtG30ZRoSO3ET8LfR1m8Y4Y4FHgSgDVDWUCNUAC/ZbvA6NIdNEKMLmpv5YWvCEMfOfpxvlTYG/tNBEfLhOi6ZzPh5zAW+C5+CiDmBHlQ+1et8nR4fhwCPX80D6Y03US2V1I8ED2j3qbqtf7lcYqGHcQ3PCwOqVMH8AdjlvFUFGxU0Ps3//rcz/gjaCjRTC3xFDC2/+1gO0AeuEuU4YEO0nlsOT6dM+xX2kdXFIgEpxMmDhCFEO9cZ9FW5ONRZxdn2iuS3uSY7cmPjv9MgibomSpRp7ylz5x83ZPxL9p8w+WuwJ9kI/w2EQkKsq3TBuQxm98yVteJpfd/GHEKv7XVscCkR9xk="
  - GH_USER_NAME: "chaostoolkit-ci"

script: 
  - bash ci.bash

branches:
  except:
  - gh-pages