language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt

env:
  global:
  - GH_USER_NAME: "chaostoolkit-ci"
  - secure: "OGk3mgmuHD5tdnC4r0Jas6mEhLrpyfLMjopi4A3kzqr6hAh3P9nQT2FDUHhGMCjV6vzX8w9Fmk0wBz0sK0UpJqfEJ+n1OuDbEemItchvsARVmva3B8zayhz2rkQzMmSCL5R+lNA4EEjaOwkT0tlHlmIl+crxP0Qrgw3vWivOXQCmeugPalczNh8VjLr51YdVxtm2UsJsp8binb3lRNqrOQrrbi++vD7mZpn6gpwjvXw7NMO5D5afuxHrApr8H0+2r0vGsDpsJNEOuzXRl96+t/MJaWuviW+L6DG+wYDMKDVed33diWrxWvR3Pz0L3VJVKjr6nDNX+QFKpjdmtxGhpDj3H9Zp3fe+5n6ihhmEbxlKRMOqWJTYkPhzD8jQ1nWpIwHzTmkysKsYTewEkeYqTO60nCeX/jVPjW6QbPxtsRV/6+ywEEO86SmCGooxx1AfnJ7MbJwjXWT2o9aILYfXCwdUBgmcNd+CdImLA9ttCO1iFHdO7c+MNS8VUxhHoozyAojxb3NfJ+7iCFkV2KLukoW6v7QV+MrjCXSXe3zmT1xnakoianAmhEeGv4I3y+s16Afiol5Gi3R3H4X1+rkAkLPytd3VXUchym7nSYQBaem1cWecl+WtV4BqaLVFSHoQp1XiAaRcBnTjE+DtGn0K8RIW4z1MvWFm0ZorATZPXLE="

script: 
  - bash ci.bash

branches:
  except:
  - gh-pages
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
