language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq

python:
  - 3.5

install:
  - pip install -r requirements.txt

env:
  global:
  - GH_USER_NAME: "chaostoolkit-ci"
  - secure: "X2TCJU7i7Fz56dGtMMsfBuPXIGxs7dK9DVSkGKxsZAMg3iw9qLGqTpeMgh+d51fcOw+/nzjHYBcfoD3cJSRFJ2ktXURN342tFBYCfVJ1lJHo7GIyUTSI1cYuflVvfygC5a/LODbZBvz549+K5A/8/7BtrmxfA3wyGgE/Goe7nANDbQ/OVmL3bmVknKxO85Iy0SDNZEydlLct6g3MIENnDxVVB2XRR+qH9FcPmw85naAe7grad//8803gWpfkke327Bcned75M4pSvGGgKK7VJmOsZwBXJ4Y5J+EoggEb6bNye3AyA2q91V+h/BNaJEr3BmMi0A47emXWvr2QUnorLp3x5gnDpFsN/4e9cdMkwqiv3og7c+rHRh7ENCn5rRYoy2+0os9CJR9LTyDP1p4AuHzVQAJqqv6zLOPRIIhbRg5QtYHb3elrslmNPB7eW3Z51l+by5cbIF6hvMV0P76wvRgpxIhPhoXE5b4IvmJtCQ98R2vC0RKZzYuF35Z7fSukv/0RzWFYMUNEiuFIXQZo9WuL45g4LAyPq9VuVxrSC6ZWpIW9sYrOEzXm+VtbCBykoQH5cV9e4rpzlnNaHXv1TiBcmT8w2S3wSZ0WKeW3Koq1bJ0iaHecSV4LacME+PQJCJmRrUw2F0Qaq8s4gqLUIsSMrXnf5ri+wAoai6ODYqk="

script: 
  - bash ci.bash

branches:
  except:
  - gh-pages
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
