site_name: Chaos Toolkit
site_author: The Chaos Toolkit Team
site_description: Chaos Toolkit
copyright: '&copy; 2017-2018 chaostoolkit team'
theme:
  name: material
  favicon: "static/images/favicon.ico"
  logo: "static/images/logo.png"
  palette:
    primary: "white"
    accent: "yellow"
extra_css:
  - 'static/css/extra.css'
docs_dir: sources
google_analytics:
  - UA-107338053-1
  - auto
repo_name: chaostoolkit
repo_url: https://github.com/chaostoolkit/chaostoolkit
markdown_extensions:
  - markdown_include.include:
      base_path: "sources/shared"
  - admonition
  - codehilite:
      guess_lang: False
      linenums: False
  - def_list
  - footnotes
  - meta
  - smarty
  - toc:
      permalink: True
  - pymdownx.betterem:
      smart_enable: "all"
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: True
  - pymdownx.tilde
extra:
  social:
    - type: github
      link: https://github.com/chaostoolkit
    - type: twitter
      link: https://twitter.com/chaostoolkit
    - type: slack
      link: https://join.chaostoolkit.org/
    - type: medium
      link: https://medium.com/chaos-toolkit
nav:
- Home: index.md
- Usage:
    - Install: reference/usage/install.md
    - Upgrade: reference/usage/upgrade.md
    - CLI:
        - Overview: reference/usage/cli.md
        - Discover: reference/usage/discover.md
        - Init: reference/usage/init.md
        - Run: reference/usage/run.md
        - Report: reference/usage/report.md
        - Notify: reference/usage/notification.md
        - Schedule: reference/usage/scheduling.md
- Deployment:
    - Kubernetes:
        - Operator: deployment/k8s/operator.md
- Tutorials:
    - Get Started with the Chaos Toolkit: reference/tutorial.md
    - Learn all about Steady-State Tolerances: reference/tutorials/tolerance.md
- Drivers Reference:
    - Overview: drivers/overview.md
    - Infrastructure/Platform:
      - AWS: drivers/aws.md
      - Azure: drivers/azure.md
      - Cloud Foundry: drivers/cloudfoundry.md
      - Google Cloud Platform: drivers/gcp.md
      - Kubernetes: drivers/kubernetes.md
      - Service Fabric: drivers/service-fabric.md
    - Application:
      - Spring: drivers/spring.md
    - Network:
      - ToxiProxy: drivers/toxiproxy.md
      - Istio: drivers/istio.md
      - WireMock: drivers/wiremock.md
    - Observability:
      - Humio: drivers/humio.md
      - Prometheus: drivers/prometheus.md
      - Open Tracing: drivers/opentracing.md
- Chaos Open API:
    - Concepts: reference/concepts.md
    - Experiment: reference/api/experiment.md
    - Journal: reference/api/journal.md
- Contribute:
    - Contributing to the Chaos Toolkit: reference/contributing.md
    - Project Management:
        - Key Project Values: reference/developing/values.md
        - Core Projects: reference/developing/core.md
        - Technology Choices: reference/developing/technologies.md
- Develop:
    - Guidelines: reference/developing/guidelines.md
    - Driver Extension:
        - Extension Approaches: reference/extending/approaches.md
        - Extend with Python: reference/extending/extending-with-python.md
    - Control Extension:
        - Create Control: reference/extending/create-control-extension.md
- Resources:
    - Logos: resources/logos.md
    - Slides: resources/slides.md
